### ISSUE TITLE
UI to show random questions from the list

### ISSUE THREAD

**Issue by shershen08** [VGraupera/1on1-questions#15]
👋 Hi! 
Some time ago I've created a simple React app that displays random questions from the list 
I am using it when I have 1-on-1s to ask various questions to my colleagues/

you can play with it here: https://compassionate-bose-f21503.netlify.app/

App repo here: https://github.com/shershen08/react-tailwind-question-generator

Thanks for this repo and hope this is useful!

**Comment by perelin** [comment]
I did not see @shershen08 version before but had the same thought :)

You can find it here https://1on1questions.netlify.app/

Feedback welcome!

**Comment by VGraupera** [comment]
Thanks, I will add these to the readme!
